### ISSUE TITLE
Example grafana dashboards?

### ISSUE THREAD

**Issue by taiyangc** [hypnoglow/go-pg-monitor#2]
Do you mind sharing the grafana dashboards you have in the README? JSON files to be easily imported? Thanks for this convenient plugin.

**Comment by taiyangc** [comment]
@hypnoglow Is it possible to release the charts? Thanks.

**Comment by hypnoglow** [comment]
Hey @taiyangc 

I think that Grafana dashboards vary based on different factors: whether you use metric namespace, whether you use one database object in your code or multiple, what Grafana version you use, what labels in k8s do you use, how do you combine metrics in one graph, etc. So I'm not sure that there is a "right" dashboard, it will be different for each user (or company).

However, I agree we could provide a dashboard just as an example, so it would be easier for people to make their own.

**Comment by taiyangc** [comment]
Thank you! @hypnoglow
